# Generated by Django 3.2 on 2021-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grade', models.SmallIntegerField(blank=True, choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Неудовлетворительно')], null=True)),
            ],
        ),
    ]
